# Generated by Django 2.1.15 on 2024-07-05 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('planta', '0001_initial'),
        ('sitios', '0001_initial'),
        ('contratacion', '0002_procedimientos_usuarioregistro'),
        ('usuarios', '0001_initial'),
        ('clinico', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicos',
            name='centro',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to='sitios.Centros'),
        ),
        migrations.AddField(
            model_name='medicos',
            name='ciudad',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to='sitios.Ciudades'),
        ),
        migrations.AddField(
            model_name='medicos',
            name='departamento',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to='sitios.Departamentos'),
        ),
        migrations.AddField(
            model_name='medicos',
            name='especialidades',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to='clinico.Especialidades'),
        ),
        migrations.AddField(
            model_name='medicos',
            name='planta',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to='planta.Planta'),
        ),
        migrations.AddField(
            model_name='medicos',
            name='tipoDoc',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to='usuarios.TiposDocumento'),
        ),
        migrations.AddField(
            model_name='interconsultas',
            name='diagnosticos',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to='clinico.Diagnosticos'),
        ),
        migrations.AddField(
            model_name='interconsultas',
            name='documento',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='DocumentoHistoriaInterconsulta', to='usuarios.Usuarios'),
        ),
        migrations.AddField(
            model_name='interconsultas',
            name='especialidadConsultada',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='clinico.Especialidades'),
        ),
        migrations.AddField(
            model_name='interconsultas',
            name='estadosInterconsulta',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to='clinico.EstadosInterconsulta'),
        ),
        migrations.AddField(
            model_name='interconsultas',
            name='plantaConsultado',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to='planta.Planta'),
        ),
        migrations.AddField(
            model_name='interconsultas',
            name='tipoDoc',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='usuarios.TiposDocumento'),
        ),
        migrations.AddField(
            model_name='incapacidades',
            name='dependenciasRealizado',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='sitios.Dependencias'),
        ),
        migrations.AddField(
            model_name='incapacidades',
            name='diagnosticos',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='clinico.Diagnosticos'),
        ),
        migrations.AddField(
            model_name='incapacidades',
            name='documento',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='DocumentoIncapacidades', to='usuarios.Usuarios'),
        ),
        migrations.AddField(
            model_name='incapacidades',
            name='tipoDoc',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='usuarios.TiposDocumento'),
        ),
        migrations.AddField(
            model_name='incapacidades',
            name='tiposIncapacidad',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='clinico.TiposIncapacidad'),
        ),
        migrations.AddField(
            model_name='historiaresultados',
            name='dependenciasRealizado',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='sitios.Dependencias'),
        ),
        migrations.AddField(
            model_name='historiaresultados',
            name='documento',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='DocumentoHistoriaResul', to='usuarios.Usuarios'),
        ),
        migrations.AddField(
            model_name='historiaresultados',
            name='estadoExamenes',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='clinico.EstadoExamenes'),
        ),
        migrations.AddField(
            model_name='historiaresultados',
            name='examen',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='clinico.Examenes'),
        ),
        migrations.AddField(
            model_name='historiaresultados',
            name='tipoDoc',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='usuarios.TiposDocumento'),
        ),
        migrations.AddField(
            model_name='historiaresultados',
            name='tiposExamen',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='clinico.TiposExamen'),
        ),
        migrations.AddField(
            model_name='historialdiagnosticoscabezote',
            name='documento',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='DocumentoHistoriaDiag', to='usuarios.Usuarios'),
        ),
        migrations.AddField(
            model_name='historialdiagnosticoscabezote',
            name='tipoDoc',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='usuarios.TiposDocumento'),
        ),
        migrations.AddField(
            model_name='historialdiagnosticos',
            name='diagnosticos',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='dxPpal', to='clinico.Diagnosticos'),
        ),
        migrations.AddField(
            model_name='historialdiagnosticos',
            name='historialDiagnosticosCabezote',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='DocumentoHistoriaDiag', to='clinico.HistorialDiagnosticosCabezote'),
        ),
        migrations.AddField(
            model_name='historialdiagnosticos',
            name='tiposDiagnostico',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='tiposDiagnostico', to='clinico.TiposDiagnostico'),
        ),
        migrations.AddField(
            model_name='historialantecedentes',
            name='antecedentes',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clinico.Antecedentes'),
        ),
        migrations.AddField(
            model_name='historialantecedentes',
            name='documento',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='DocumentoAntecedentes', to='usuarios.Usuarios'),
        ),
        migrations.AddField(
            model_name='historialantecedentes',
            name='tipoDoc',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='usuarios.TiposDocumento'),
        ),
        migrations.AddField(
            model_name='historialantecedentes',
            name='tiposAntecedente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clinico.TiposAntecedente'),
        ),
        migrations.AddField(
            model_name='historialantecedentes',
            name='usuarioRegistro',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to='usuarios.Usuarios'),
        ),
        migrations.AddField(
            model_name='historiaexamenescabezote',
            name='historia',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='clinico.Historia'),
        ),
        migrations.AddField(
            model_name='historiaexamenescabezote',
            name='tiposExamen',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='clinico.TiposExamen'),
        ),
        migrations.AddField(
            model_name='historiaexamenes',
            name='estadoExamenes',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='clinico.EstadoExamenes'),
        ),
        migrations.AddField(
            model_name='historiaexamenes',
            name='historiaExamenesCabezote',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='clinico.HistoriaExamenesCabezote'),
        ),
        migrations.AddField(
            model_name='historiaexamenes',
            name='procedimientos',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='contratacion.Procedimientos'),
        ),
        migrations.AddField(
            model_name='historia',
            name='causasExterna',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='clinico.CausasExterna'),
        ),
        migrations.AddField(
            model_name='historia',
            name='dependenciasRealizado',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='sitios.Dependencias'),
        ),
        migrations.AddField(
            model_name='historia',
            name='documento',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='DocumentoHistoria', to='usuarios.Usuarios'),
        ),
        migrations.AddField(
            model_name='historia',
            name='especialidades',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='clinico.Especialidades'),
        ),
        migrations.AddField(
            model_name='historia',
            name='planta',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='planta.Planta'),
        ),
        migrations.AddField(
            model_name='historia',
            name='tipoDoc',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='usuarios.TiposDocumento'),
        ),
        migrations.AddField(
            model_name='historia',
            name='tiposFolio',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='clinico.TiposFolio'),
        ),
        migrations.AddField(
            model_name='historia',
            name='usuarioRegistro',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to='usuarios.Usuarios'),
        ),
        migrations.AddField(
            model_name='examenes',
            name='TiposExamen',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='clinico.TiposExamen'),
        ),
        migrations.AddField(
            model_name='especialidadesmedicos',
            name='especialidades',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='especialidadesMedicos1', to='clinico.Especialidades'),
        ),
        migrations.AddField(
            model_name='especialidadesmedicos',
            name='planta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='planta.Planta'),
        ),
        migrations.AddField(
            model_name='especialidadesmedicos',
            name='usuarioRegistro',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='usuarioRegistroPlanta', to='planta.Planta'),
        ),
        migrations.AddField(
            model_name='antecedentes',
            name='tiposAntecedente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='clinico.TiposAntecedente'),
        ),
    ]
