# Generated by Django 2.1.15 on 2024-07-05 19:38

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinico', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Procedimientos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cups', models.CharField(default=0, max_length=20)),
                ('nombre', models.CharField(max_length=80)),
                ('solicitaEnfermeria', models.CharField(choices=[('S', 'Si'), ('N', 'No')], max_length=1)),
                ('fechaRegistro', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('estadoReg', models.CharField(default='A', editable=False, max_length=1)),
                ('tiposExamen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clinico.TiposExamen')),
            ],
        ),
    ]
