# Generated by Django 2.1.15 on 2024-07-05 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingresos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('consec', models.IntegerField()),
                ('fechaIngreso', models.DateTimeField(blank=True, null=True)),
                ('fechaSalida', models.DateTimeField(blank=True, null=True)),
                ('factura', models.IntegerField(default=0)),
                ('numcita', models.IntegerField(default=0)),
                ('salidaClinica', models.CharField(default='N', max_length=1)),
                ('salidaDefinitiva', models.CharField(default='N', max_length=1)),
                ('muerte', models.CharField(default='N', max_length=1)),
                ('fechaMuerte', models.DateTimeField(blank=True, null=True)),
                ('ActaDefuncion', models.CharField(default='', max_length=30)),
                ('fechaRegistro', models.DateTimeField(blank=True, null=True)),
                ('estadoReg', models.CharField(default='A', editable=False, max_length=1)),
            ],
        ),
    ]
