# Generated by Django 2.1.15 on 2024-07-05 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('planta', '0001_initial'),
        ('sitios', '0001_initial'),
        ('usuarios', '0001_initial'),
        ('admisiones', '0002_auto_20240705_1438'),
        ('clinico', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingresos',
            name='dependenciasActual',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sitios.Dependencias'),
        ),
        migrations.AddField(
            model_name='ingresos',
            name='dependenciasIngreso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='id0', to='sitios.Dependencias'),
        ),
        migrations.AddField(
            model_name='ingresos',
            name='dependenciasSalida',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='id2', to='sitios.Dependencias'),
        ),
        migrations.AddField(
            model_name='ingresos',
            name='documento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Documento', to='usuarios.Usuarios'),
        ),
        migrations.AddField(
            model_name='ingresos',
            name='dxActual',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='id4', to='clinico.Diagnosticos'),
        ),
        migrations.AddField(
            model_name='ingresos',
            name='dxIngreso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='id3', to='clinico.Diagnosticos'),
        ),
        migrations.AddField(
            model_name='ingresos',
            name='dxSalida',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='id5', to='clinico.Diagnosticos'),
        ),
        migrations.AddField(
            model_name='ingresos',
            name='especialidadesMedicosActual',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='EspAct', to='clinico.Especialidades'),
        ),
        migrations.AddField(
            model_name='ingresos',
            name='especialidadesMedicosIngreso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='EspIng', to='clinico.Especialidades'),
        ),
        migrations.AddField(
            model_name='ingresos',
            name='especialidadesMedicosSalida',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='EspSal', to='clinico.Especialidades'),
        ),
        migrations.AddField(
            model_name='ingresos',
            name='estadoSalida',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='clinico.EstadosSalida'),
        ),
        migrations.AddField(
            model_name='ingresos',
            name='hClinica',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='usuarios.Usuarios'),
        ),
        migrations.AddField(
            model_name='ingresos',
            name='medicoActual',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='id7', to='planta.Planta'),
        ),
        migrations.AddField(
            model_name='ingresos',
            name='medicoDefuncion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='clinico.Medicos'),
        ),
        migrations.AddField(
            model_name='ingresos',
            name='medicoIngreso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='id6', to='planta.Planta'),
        ),
        migrations.AddField(
            model_name='ingresos',
            name='medicoSalida',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='id8', to='planta.Planta'),
        ),
        migrations.AddField(
            model_name='ingresos',
            name='regimen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='clinico.Regimenes'),
        ),
        migrations.AddField(
            model_name='ingresos',
            name='salidaMotivo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='EspSal', to='clinico.TiposSalidas'),
        ),
        migrations.AddField(
            model_name='ingresos',
            name='sedesClinica',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='SedesClinica', to='sitios.SedesClinica'),
        ),
        migrations.AddField(
            model_name='ingresos',
            name='tipoDoc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='usuarios.TiposDocumento'),
        ),
        migrations.AddField(
            model_name='ingresos',
            name='tiposCotizante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='clinico.TiposCotizante'),
        ),
        migrations.AddField(
            model_name='ingresos',
            name='usuarioRegistro',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to='planta.Planta'),
        ),
    ]
