# Generated by Django 2.1.15 on 2024-07-05 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('seguridad', '0001_initial'),
        ('sitios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilesclinica',
            name='sedesClinica',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='SedesClinicaSeguridad', to='sitios.SedesClinica'),
        ),
        migrations.AddField(
            model_name='moduloselementosdef',
            name='modulosElementosId',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to='seguridad.ModulosElementos'),
        ),
        migrations.AddField(
            model_name='moduloselementosdef',
            name='modulosId',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to='seguridad.Modulos'),
        ),
    ]
